// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  apiSidebar: [
    {
      type: "category",
      label: "Referencia de la API",
      className: "sidebar-section-api",
      link: {
        type: "generated-index",
        title: "Referencia de la API",
        description: "Documentación técnica detallada de todos los endpoints y módulos de la API de Ambrosia POS.",
        slug: "/api-reference",
      },
      items: [{ type: "autogenerated", dirName: "API" }],
    },
    {
      type: "category",
      label: "Portal de Desarrolladores",
      className: "sidebar-section-dev",
      link: {
        type: "generated-index",
        title: "Portal de Desarrolladores",
        description: "Recursos, guías y estándares para contribuir al ecosistema de Ambrosia POS.",
        slug: "/developer-portal",
      },
      items: [{ type: "autogenerated", dirName: "Development" }],
    },
  ],
  phoenixSidebar: [{ type: "autogenerated", dirName: "Phoenixd" }],
};

export default sidebars;
